{
    'name': "Vertical Hospital",
    'summary': """""",
    'description': """
        Vertical Hospital Management System
    """,
    'author': "Ricardo Oviedo",
    'website': "",
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': ['base', 'mail'],
    'data': [
        # 'data/groups.xml',
        'data/sequences.xml',
        'security/ir.model.access.csv',
        'views/intro.xml',
        'views/patients.xml',
        'views/treatments.xml',
        'views/res_config_settings_hospital.xml',
        'data/menus.xml',
        # 'views/types_action.xml',
        # 'views/send_to_payroll.xml',
        # 'views/res_config_settings_views.xml',
        # 'views/hr_employee.xml',
        # 'views/hr_contract_view.xml',
        # 'wizard/request_pa_denied_wizard.xml',
        # 'data/requested_pa_template.xml',
        # 'data/leader_pa_template.xml',
        # 'data/requested_pa_action_template.xml',
        # 'data/hr_pa_action_template.xml',
        # 'data/max_extra_hours_cron.xml',
        'reports/patients_report.xml',
        'reports/list_patients_report.xml',
    ],
    'demo': [],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
}
# -*- coding: utf-8 -*-
